### ISSUE TITLE
Dynamic background color (follows the system's light/dark theme)

### ISSUE THREAD

**Issue by o000u** [Kolcha/DigitalClockNext#10]
Hi @Kolcha !
I am using macOS system. When I set the appearance as font instead of skin and remove the texture check, the font of the clock will automatically change color according to the system's light/dark theme, but the background cannot. Currently, it can only be a single color. Can the background also automatically change color according to the system's light/dark theme?

Good day!

**Comment by Kolcha** [comment]
helo

technically, the fact that fonts follow the system theme is just a side effect :) this is not a thing that was intentionally implemented :) I didn't think that someone discover it and use :)

what about the background, no background is assumed, so it doesn't use the system colors. this requires some development, but it should not be hard to implement. will look into this when will have free time, very likely closer to the weekend.

**Comment by o000u** [comment]
> helo
> 
> technically, the fact that fonts follow the system theme is just a side effect :) this is not a thing that was intentionally implemented :) I didn't think that someone discover it and use :)
> 
> what about the background, no background is assumed, so it doesn't use the system colors. this requires some development, but it should not be hard to implement. will look into this when will have free time, very likely closer to the weekend.

Haha, maybe this time you can let everyone know about the font "special feature" ^ _ ^~~~Thank you for your prompt reply, looking forward to your progress, thank you!

**Comment by o000u** [comment]
今天收到更新通知，居然出5.0了，兴奋！
第一时间更新了，对中文的支持真的超好评！👍🏻
设置UI也更加美观友好，插件的加入也让软件更具乐趣和实用，作者辛苦了！🤝

就是好像【背景颜色随系统亮/暗主题自动切换】依然没有哈？^_^

**Comment by o000u** [comment]
![2024-09-13_11-05-20](https://github.com/user-attachments/assets/25399ec6-6fbd-4436-b32f-45a549349982)
另外，似乎5.0在拖放位置靠屏幕边缘的时候会强制自动贴边，不能自由微调了，能否加个选项让用户选择是否自动贴边？
又或者，让用户自由调整时钟红色虚线边框的边距大小？

**Comment by o000u** [comment]
> ![2024-09-13_11-05-20](https://private-user-images.githubusercontent.com/33189913/367135902-25399ec6-6fbd-4436-b32f-45a549349982.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDEwNjgsIm5iZiI6MTcyNjIwMDc2OCwicGF0aCI6Ii8zMzE4OTkxMy8zNjcxMzU5MDItMjUzOTllYzYtNmZiZC00NDM2LWIzMmYtNDVhNTQ5MzQ5OTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA0MTI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYzVkODhiMDBjNmE2OGJmMDU3NDQ5NWY1Y2M4OTQ1YThkZDE1MzAwNzBjN2YzZDFiYzViYTFjNzJjYjlmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NR0P5J3q0GohqIOyH00nYuqZc0m5I5nL0bsYCoR-gsY) 另外，似乎5.0在拖放位置靠屏幕边缘的时候会强制自动贴边，不能自由微调了，能否加个选项让用户选择是否自动贴边？ 又或者，让用户自由调整时钟红色虚线边框的边距大小？

回看了下旧版本，发现是有这个选项的：
![Uploading 2024-09-13_12-16-18.png…]()

**Comment by Kolcha** [comment]
yes, 5.0 is here. and it also was written completely from scratch and it is going to replace the old Digital Clock 4. so, interface was intentionally made similar to the old one. this "Next" version will be deprecated soon, as I port some unique stuff from it to 5.0

regarding Chinese: I don't know it, even though it may seem that I do :) (I have to deal with it surprisingly often, even considered learning it several times, but not have so much time for it, unfortunately). it is available just because I imported translation from Digital Clock 4 and interface has many same strings as old version (intentionally). that's why it is only partially translated, [feel free to improve it](https://github.com/Kolcha/DigitalClock5/wiki/Translate)

and yes, automatic background switching is still not available, even text color switching is very likely lost due to a completely new engine. but this feature was kept in mind during design and will be definitely implemented. I even will expand it to all skins, not only text (yes, it will be possible to use system text color for any image-based skin).

**Comment by o000u** [comment]
> about "snap to edge" option: yes, for now it is hardcoded, and snaps to the screen edge when clock is 15px to it. options to enable/disable it and also for fine-tuning this threshold will be added later, this is one of low-priority tasks.
> 
> about the margins around the clock: there are several issues involved, and the main one is not controlled by me. many modern fonts have a lot of unnecessary spacing around the characters, my clock uses these font metrics to build that nice-looking string, so spacing is just inherited. also the publicly available version actually has some extra margins around the clock, they were removed [recently](https://github.com/Kolcha/DigitalClock5/commit/dfa7726f377722047dde914d4d360cb31eb8ef6e), the changes will be included in the next version (this weekend).
> 
> my primary focus nowadays is bugfixing (likely users reported many significant issues), as the code was written in less than 2 weeks when I was in a very bad psychological state (writing code significantly helped me), and it is almost not tested, so many bugs are possible. as result, new releases including important bug fixes will happen quite often for now, but different minor features that are easy to implement also will be included. most of the "bigger features" are planned in 5.1 or so.

Got it.

**Comment by Kolcha** [comment]
option added! it is available for any skin
solid color should be selected to get it
<img width="707" alt="Screenshot 2024-09-14 at 15 01 42" src="https://github.com/user-attachments/assets/a70bb2a5-bc76-406f-9280-715f8edeab32">
