### ISSUE TITLE
Quick note forget content

### ISSUE THREAD

**Issue by Li-An** [Kolcha/DigitalClockNext#11]
Hello, the plugin system is top but I meet a problem with Quick Note plugin. It does not remember the content if I turn off my computer.

**Comment by Kolcha** [comment]
thanks for the report, will take a look what is wrong here.

by the way, you reported to the wrong repo :)
it should be https://github.com/Kolcha/DigitalClock5 , not "Next". "Next" doesn't have plugin system.

maybe I need to check links everywhere :), or even archive this "Next" repository, it is not supposed to be supported for a long time and shut down pretty soon as I migrate new stuff that appeared in this "Next" version to DigitalClock 5.

**Comment by Li-An** [comment]
Sorry for that mistake. The different versions are a little confusing. When I installed the DC5, I wondered why I had two clocks showing - Next and 5 version.
