### ISSUE TITLE
Great app! Can you add a function to hide the clock when the mouse moves over it?

### ISSUE THREAD

**Issue by o000u** [Kolcha/DigitalClockNext#3]
Hi Kolcha!
As the title says, that will allow me to more naturally see and click on the window area covered by the clock.
Thanks for your effort, this is a really great app that solves the problem of watching the time when the menu bar is hidden!

**Comment by Kolcha** [comment]
such option is planned, I'll add it. but this requires platform-specific tricks, so in today's world this definitely may work unreliable, unfortunately...

**Comment by o000u** [comment]
> such option is planned, I'll add it. but this requires platform-specific tricks, so in today's world this definitely may work unreliable, unfortunately...

Thank you for your reply! 
I look forward to seeing the implementation of this function soon. I hope everything goes well. 
Good luck and Good day!
