### ISSUE TITLE
Move clock ?

### ISSUE THREAD

**Issue by Li-An** [Kolcha/DigitalClockNext#5]
Hello, I feel a little dumb because I cannot manage to move the clock - I had no problem with old version. What did I miss ?

**Comment by Kolcha** [comment]
please, specify the system you are using. on mac and windows there are should be no problems with it (unless something has changed inside the systems, I'm rarely using them).

if you are on Linux with Wayland - no move is possible, this is by [Wayland's design](https://stackoverflow.com/questions/67318357/how-to-set-the-position-of-a-wayland-window-on-the-screen).

in any case, make sure that "transparent for mouse events" option is disabled, if not - disable it and restart the app (unfortunately restart is required nowadays), than clock will be movable.

**Comment by Li-An** [comment]
Thanks. I did not think to restart after changing the setting.
